import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by Soinov Michel",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={montserrat.className}>
        <Header className="header"/>
           <main>{children}</main>
        {/* <Footer className="footer"/> */}
      </body>
    </html>
  );
}
